# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-26 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='email',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='url',
        ),
        migrations.AddField(
            model_name='comment',
            name='phone',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='comment',
            name='unit',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
