# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-23 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20171023_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.IntegerField(choices=[(0, '显示'), (1, '隐藏')], default=0, editable=False, verbose_name='状态'),
        ),
    ]
