# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 06:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20171031_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalog',
            name='post',
        ),
    ]
