# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 07:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20171031_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='catalog',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.Catalog'),
        ),
    ]
