# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-01 01:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20171031_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='catalog',
            field=models.ForeignKey(default=16, on_delete=django.db.models.deletion.CASCADE, to='blog.Catalog', verbose_name='目录'),
        ),
    ]
