# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-01 01:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20171101_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='catalog',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.Catalog', verbose_name='目录'),
        ),
    ]
